field: 4a9bd924-5286-41f7-a746-63a7cdb4c320 # Blog Content
fieldLayouts:
  830c568b-36e3-49de-9c38-c2b88b9e54e8:
    tabs:
      -
        elements:
          -
            fieldUid: 53b1357b-f1f4-4f29-be51-cff0916f1587 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  53b1357b-f1f4-4f29-be51-cff0916f1587: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:96aae4a6-7ecf-4c62-bd48-416cebc9c2b9' # Portfolio Images
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an Image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:96aae4a6-7ecf-4c62-bd48-416cebc9c2b9' # Portfolio Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: media
name: Media
sortOrder: 2
