fieldLayouts:
  50286095-fb97-41d0-bc82-8f6d8c283614:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 152ffa73-8e4d-4479-8163-4b2615b92f59
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8d107c75-10b2-49ca-972c-5a37a243c9cc
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ef54f9fc-18aa-4b10-9a74-7ce95a4c8af9
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Hero Area'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 435c7f33-e768-448e-87ed-8d9134357c81
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8ca281a7-576c-4e0b-8eeb-5e1e7bcaa3b7
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'About Me Area'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: b73bc268-3c60-4f68-b01c-c1f78495ac0a
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b52a3c47-77c2-4b77-a03b-50b692ead9e9
            required: true
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 53be00a5-a83e-4dee-842b-ea253605d04b
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: 'Core Skills Area'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: efac94ae-c2c8-4b53-bc37-d6d1c319be75
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9cc350ac-4753-4489-b49b-0e285d596baf
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Skills List Area'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 90d286fe-a8e3-40f3-b973-3c8185e0c821
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Work Showcase'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 6b530948-c709-4133-b20a-626f755326f5
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 6
handle: homepage
hasTitleField: false
name: Homepage
section: 0c7536fe-d210-4c25-b286-ef8b7260b95e
sortOrder: 1
titleFormat: Homepage
