handle: portfolioCategory
name: 'Portfolio Category'
siteSettings:
  3af667cd-f79e-4ed4-b209-421713d485f6:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: e0c04416-8e99-4ff4-acae-710a31478635
