contentColumnType: text
fieldGroup: 2eca9b7d-c919-4178-b23f-742837bdc05a
handle: heroSkillsList
instructions: ''
name: 'Hero Skills List'
searchable: true
settings:
  addRowLabel: 'Add a skill'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Skill Name'
            -
              - handle
              - skillName
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    __assoc__:
      -
        - row1
        -
          __assoc__:
            -
              - col1
              - ''
  maxRows: '3'
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
