contentColumnType: text
fieldGroup: 2eca9b7d-c919-4178-b23f-742837bdc05a
handle: heroSubTitle
instructions: ''
name: 'Hero Sub-Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
