contentColumnType: string
fieldGroup: 502cea6f-b329-4f5a-9c51-f03e6f23163f
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:96aae4a6-7ecf-4c62-bd48-416cebc9c2b9'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'Add an image'
  singleUploadLocationSource: 'volume:96aae4a6-7ecf-4c62-bd48-416cebc9c2b9'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
