columnSuffix: null
contentColumnType: string
fieldGroup: 2eca9b7d-c919-4178-b23f-742837bdc05a
handle: recentWork
instructions: ''
name: 'Recent Work'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:ad72cd36-126a-4681-ac7b-8bf45e5da129' # Case Studies
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
