columnSuffix: hxchmzve
contentColumnType: text
fieldGroup: 502cea6f-b329-4f5a-9c51-f03e6f23163f
handle: responsibilities
instructions: ''
name: Responsibilities
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
