dateModified: 1644012237
email:
  fromEmail: JJimmyFlynn@gmail.com
  fromName: JohnJFlynn
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a6cd492-5ea0-4783-ba58-b0ea1cd685e3: 'Case Study Image' # Case Study Image
    2ff5cab0-a543-45b8-b411-bcdbd77a544e: Portfolio # Portfolio
    3a66485e-ef06-4d57-bf31-67fac8147202: 'Case Study Excerpt' # Case Study Excerpt
    3af667cd-f79e-4ed4-b209-421713d485f6: JohnJFlynn # JohnJFlynn
    3ecb3ea5-33e8-4591-8b88-55143d685317: Text # Text
    3f46a0a7-5ad4-492b-b4b7-bdde50823f77: 'Case Study Link' # Case Study Link
    4a9bd924-5286-41f7-a746-63a7cdb4c320: 'Blog Content' # Blog Content
    5d195f08-e837-4e08-9504-1fd7c557d060: Media # Media
    8a074c7a-a5f4-4fd3-b490-7cdf070ec6bd: Text # Text
    53b1357b-f1f4-4f29-be51-cff0916f1587: Images # Images
    96aae4a6-7ecf-4c62-bd48-416cebc9c2b9: 'Portfolio Images' # Portfolio Images
    351b2d7f-eb97-4608-939d-632858c0c4be: Heading # Heading
    66354ef9-cb91-42db-9351-02e34fad4ca3: 'Recent Work' # Recent Work
    77232c91-c326-4586-a3fb-5973a9843126: Homepage # Homepage
    ad72cd36-126a-4681-ac7b-8bf45e5da129: 'Case Studies' # Case Studies
    b6a18b8c-5ef1-4c3c-978a-9abdb0dd610d: Default # Default
    b135dc5d-315d-430a-a85f-7d8d9a6e0e75: 'Alt Text' # Alt Text
    c6456822-0dc1-4aa2-8d57-3acf5f2a07ef: 'Header Settings' # Header Settings
    f2d9f8c5-f465-4a10-9270-efa665555932: Responsibilities # Responsibilities
plugins:
  admin-bar:
    enabled: '1'
    licenseKey: null
    schemaVersion: 3.1.0
    settings:
      customCss: ''
      customLinks:
        -
          adminOnly: ''
          linkLabel: ''
          linkUrl: ''
      displayDashboardLink: true
      displayDefaultEditSection: true
      displayEditAuthor: true
      displayEditDate: true
      displayGreeting: true
      displayLogout: true
      displayRevisionNote: true
      displaySettingsLink: true
      enableMobileMenu: true
      widgets:
        admin-bar_edit-links: '1'
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: 6J1KK04D6TU3GX6G8XNUICJ8
    schemaVersion: 3.0.0
  palette:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    enabled: '1'
    licenseKey: null
    schemaVersion: 2.3.0
    settings: null
  seo:
    enabled: '1'
    licenseKey: null
    schemaVersion: 3.2.0
    settings:
      metaTemplate: ''
      robots:
        - noindex
        - nofollow
        - noarchive
        - nosnippet
        - notranslate
        - noimageindex
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ \".xml\") }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.general.devMode %}\r\n\r\n{# Disallow access to everything when in devMode #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      titleSuffix: ''
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 2.0.5
    settings:
      assetsEnvironment: ''
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: always
      disableDynamic: ''
      disableTransforms: ''
      injectCors: ''
      projectSlug: ''
      securityKey: ''
      suppressWarnings: '1'
      useLocalVolumes: ''
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typogrify:
    enabled: '1'
    licenseKey: null
    schemaVersion: 1.0.0
    settings: null
system:
  edition: solo
  live: true
  name: JohnJFlynn
  schemaVersion: 3.7.8
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
