fieldLayouts:
  74e59197-37bf-4539-b1cd-3e97266eedd3:
    tabs:
      -
        elements:
          -
            fieldUid: 6207bd85-012b-427e-8c97-e242a026348b
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b6e5862f-69be-42b2-87b6-34b9ae50d36c
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: General
        sortOrder: 1
handle: headerSettings
name: 'Header Settings'
