currLabel: 'Plugin Store'
customIcon: null
enabled: '1'
handle: plugin-store
icon: plugin
layoutId: '1'
newWindow: '0'
order: '8'
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: '0'
url: plugin-store
