currLabel: SEO
customIcon: null
enabled: '1'
handle: seo
icon: /home/forge/beta.johnjflynn.net/vendor/ether/seo/src/icon-mask.svg
layoutId: '1'
newWindow: '0'
order: '5'
prevLabel: SEO
prevUrl: seo
type: '0'
url: seo
