enableVersioning: true
handle: homepage
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  3af667cd-f79e-4ed4-b209-421713d485f6:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
